### PR TITLE
Adopt UEFI in Windows 2k12, 2k16 and 2k19

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Adopt UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective preferences.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Adopted UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective preferences.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
@0xFelix awesome! can you add a releasenote and then this lgtm!

/approve
/hold

**Comment by dominikholler** [comment]
@stu-gott please help to keep the common-instancetype in sync to the common-templates. When is the change to common-templates expected to happen?

**Comment by stu-gott** [comment]
/hold

Why was secureboot introduced as part of this change? SecureBoot and UEFI are independent.

/cc @acardace

**Comment by lyarwood** [comment]
> /hold
> 
> Why was secureboot introduced as part of this change? SecureBoot and UEFI are independent.
> 
> /cc @acardace

Not within our API, by default if you enable EFI you get secureboot:

https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#biosuefi

> Enabling EFI automatically enables [Secure Boot](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot), unless the secureBoot field under efi is set to false.

**Comment by stu-gott** [comment]
@dominikholler to answer your question directly, we're aiming for making the change soon. Hopefully, within the next month-ish.

**Comment by acardace** [comment]
> > /hold
> > Why was secureboot introduced as part of this change? SecureBoot and UEFI are independent.
> > /cc @acardace
> 
> Not within our API, by default if you enable EFI you get secureboot:
> 
> https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#biosuefi
> 
> > Enabling EFI automatically enables [Secure Boot](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot), unless the secureBoot field under efi is set to false.

Yes, but you can still opt-out. Do we need secureboot for Windows? @stu-gott @fabiand

**Comment by stu-gott** [comment]
In my mind, switching to UEFI is already such a major change that also adding SB is a non-issue from a technical complexity point of view. Since Windows ships vendor keys for all active versions, there should be no problem with enabling it.

**Pull request merged**
