### PR TITLE
Introduce preference resource requirements

### LINKED ISSUE #51: Resolve TODOs in `functest.sh`
/kind bug

**What happened**:

https://github.com/kubevirt/common-instancetypes/blob/dc8be11a826ff87fba641a4910d409a9e56ddc64/scripts/functest.sh#L24-L25

https://github.com/kubevirt/common-instancetypes/blob/dc8be11a826ff87fba641a4910d409a9e56ddc64/scripts/functest.sh#L55-L56

### LINKED ISSUE #55: Add minimum resource requirements to each preference
/kind enhancement

**What happened**:

https://github.com/kubevirt/kubevirt/pull/8780

As supported in `v1beta1` add these to the resources generated by the project.

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55, fixes #51

**Special notes for your reviewer**:

Based on https://github.com/kubevirt/common-instancetypes/pull/57

**Release note**:

```release-note
Resource requirements have been added to each of the supplied preference resources.
```

### CODE REVIEW

**Comment by ksimon1** [comment]
How will you make sure the requirement are up to date?

**Comment by lyarwood** [comment]
> How will you make sure the requirement are up to date?

Great question, I had forgotten to document https://github.com/kubevirt/common-instancetypes/issues/59 and a move to `osinfo` in the future as with `common-templates`. I think hard coded values are fine for now however given the support status downstream and the fact these aren't deployed as yet by default upstream.

**Comment by ksimon1** [comment]
/lgtm
For now, the hard coded values are ok

**Review by 0xFelix — APPROVED** [review]
Thanks!

/approve
/lgtm

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
