### PR TITLE
Introduce a new `NW` Network instance type family

### LINKED ISSUE #40: Introduce network workload specific instance types
/kind enhancement

As set out in the following PR for @fabiand's version of common-instancetypes a network specific workload instance type would be useful:

https://github.com/fabiand/instanceTypes/pull/3

Note this includes renaming the neutral / generic instance types.

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

Introduces a new `NW` class of Network specific instance types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #40

**Special notes for your reviewer**:

Based on https://github.com/kubevirt/common-instancetypes/pull/57

**Release note**:

```release-note
A new `NW` class of instance types has been introduced focused on `Network Intensive` workloads.
```

### CODE REVIEW

**Comment by fabiand** [comment]
Hm. Not `n1`?

**Comment by lyarwood** [comment]
> Hm. Not `n1`?

If https://github.com/kubevirt/common-instancetypes/pull/63 lands I'll switch this over to `n`.

**Comment by 0xFelix** [comment]
/close

Closed in favor of #123

**Pull request closed without merging**
