### PR TITLE
chore(deps): Bump go.mod

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/hold

I'll sort project-infra out now.

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Comment by lyarwood** [comment]
> @lyarwood I saw this error in the past. Try updating the golangci-lint to latest.

Yup thanks, should be fixed now if you could take a look @jcanocan

**Pull request merged**
