### PR TITLE
schema: Pin v0.1.0 to KubeVirt v0.59.0

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This should be automated in the future but for now manually pin KUBEVIRT_VERSION to v0.59.0 and run `make schema`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/hold

We don't have CI on this branch, I'll fix it up when I'm back next week.

**Comment by lyarwood** [comment]
https://github.com/kubevirt/project-infra/pull/2652

**Review by 0xFelix — APPROVED** [review]
/approve

**Pull request merged**
