### PR TITLE
Remove the deprecated `centos.7` and `centos.stream8` preferences

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

Both sets of preferences were deprecated back with release v1.1.0 and can now be removed from the project.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
The deprecated `centos.7` and `centos.stream8` preferences have been removed from the project.
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Since common-instancetypes are now deployed by virt-operator by default, we have to deactivate the deployment for this repo again in order to obtain meaningful CI results. :)

**Comment by lyarwood** [comment]
> Since common-instancetypes are now deployed by virt-operator by default, we have to deactivate the deployment for this repo again in order to obtain meaningful CI results. :)

/o\

https://github.com/kubevirt/common-instancetypes/pull/271

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
