### PR TITLE
Remove deprecated GN instance type class

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
The deprecated `gn` or `GPU NVIDIA` class of instance types has been removed from the project
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
Quick grep shows GN instance types are still mentioned here in `docs/labels.md`. Otherwise looks good.

**Review by 0xFelix — COMMENTED** [review]
Do we still need the GPU tests in `tests/unittests/instancetype_test.go`? Also `scripts/deploy-kubevirt-and-cdi.sh` should be adjusted to drop the `GPU` feature gate.

**Comment by lyarwood** [comment]
> Do we still need the GPU tests in `tests/unittests/instancetype_test.go`? Also `scripts/deploy-kubevirt-and-cdi.sh` should be adjusted to drop the `GPU` feature gate.

Apologies thought I had removed these tests already, also missed the FGs being used in #276.

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
