### PR TITLE
Add dependabot configuration for tests

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Add dependabot configuration for tests. This updates the dependencies on a weekly basis.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by jcanocan** [comment]
@0xFelix Just one question, why limiting it to `/test`? Can't the whole project benefit from keeping the deps up to date?

**Comment by 0xFelix** [comment]
Only `tests` is using golang in this repo.

**Comment by jcanocan** [comment]
> Only `tests` is using golang in this repo.

Undestood! Thanks!
/lgtm

**Pull request merged**
