### PR TITLE
Add SUSE Linux Enterprise Server (SLES) preference

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

$subject.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
A SUSE Linux Enterprise Server (SLES) preference has been added
```

### CODE REVIEW

**Comment by lyarwood** [comment]
This is passing locally for me with a SLES 15 SP6 minimal VM image used to seed a containerdisk and the single SLES test focused:

```
$ podman build . -f sles.Dockerfile -t sles-container-disk
[..]
$ podman push localhost/sles-container-disk docker://$(../../scripts/kubevirtci.sh registry)/sles-container-disk
[..]
$ cd ../../
$ make cluster-functest
cd tests && KUBECONFIG=$(../scripts/kubevirtci.sh kubeconfig) go test -v -timeout 0 ./functests/... -ginkgo.v -ginkgo.randomize-all 
+ export KUBEVIRT_DEPLOY_NFS_CSI=true
+ KUBEVIRT_DEPLOY_NFS_CSI=true
+ export KUBEVIRT_MEMORY_SIZE=16384
+ KUBEVIRT_MEMORY_SIZE=16384
++ curl -sfL https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirtci/latest
+ export KUBEVIRTCI_TAG=2407021046-5fcafc4
+ KUBEVIRTCI_TAG=2407021046-5fcafc4
+ export KUBEVIRT_DEPLOY_CDI=true
+ KUBEVIRT_DEPLOY_CDI=true
+ export KUBEVIRT_VERSION=main
+ KUBEVIRT_VERSION=main
+++ dirname ../scripts/kubevirtci.sh
++ cd ../scripts/..
++ pwd
+ _base_dir=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes
+ _cluster_up_dir=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up
+ _virtctl_dir=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up/_out/cmd/virtctl
+ _kubectl=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up/cluster-up/kubectl.sh
+ _kubessh=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up/cluster-up/ssh.sh
+ _kubevirtcicli=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up/cluster-up/cli.sh
+ _virtctl=/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up/cluster-up/virtctl.sh
+ _action=kubeconfig
+ shift
+ kubevirtci::fetch_kubevirtci
+ [[ ! -d /home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up ]]
+ case ${_action} in
+ kubevirtci::kubeconfig
+ /home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/_cluster-up/cluster-up/kubeconfig.sh
=== RUN   TestFunctional
Running Suite: Functional test suite - /home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/tests/functests
========================================================================================================================
Random Seed: 1720012782 - will randomize all specs

Will run 1 of 19 specs
------------------------------
[BeforeSuite] 
/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/tests/functests/test_suite_test.go:113
[BeforeSuite] PASSED [0.026 seconds]
------------------------------
SSSSSSSSSSS
------------------------------
Common instance types func tests VirtualMachine using a preference is able to boot a Linux guest with [test_id:TODO] SLES 15
/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/tests/functests/instancetype_test.go:127
{"component":"","level":"error","msg":"Cannot retrieve GuestOSInfo: an error on the server (\"Operation cannot be fulfilled on virtualmachineinstance.kubevirt.io \\\"test-vm-ml4k9\\\": VMI does not have guest agent connected\") has prevented the request from succeeding","pos":"vmi.go:431","timestamp":"2024-07-03T13:19:52.126514Z"}
{"component":"","level":"error","msg":"Cannot retrieve GuestOSInfo: an error on the server (\"Operation cannot be fulfilled on virtualmachineinstance.kubevirt.io \\\"test-vm-ml4k9\\\": VMI does not have guest agent connected\") has prevented the request from succeeding","pos":"vmi.go:431","timestamp":"2024-07-03T13:20:02.132696Z"}
• [40.257 seconds]
------------------------------
SSSSSSS
------------------------------
[AfterSuite] 
/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/tests/functests/test_suite_test.go:138
[AfterSuite] PASSED [0.001 seconds]
------------------------------
[ReportAfterSuite] TestFunctional
/home/lyarwood/redhat/devel/src/k8s/kubevirt/common-instancetypes/tests/functests/test_suite_test.go:146
[ReportAfterSuite] PASSED [0.000 seconds]
------------------------------

Ran 1 of 19 Specs in 40.285 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 18 Skipped
```

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Pull request merged**
