### PR TITLE
chore: Vendor golang tools

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Vendor the golang tools used by the build in the ./tools subdirectory. This allows reproducible builds without the need for a container image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
Isn't it enough to use only `go install` with the correct version, without adding `tools` package?

**Comment by 0xFelix** [comment]
Following this guide on how to track the tool dependencies: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by akrejcir** [comment]
> Following this guide on how to track the tool dependencies: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

The lase paragraph says:
> You can also (since go 1.16) use go install tool@version, which will install a specific version, or (since go 1.17) go run tool@version, which will run the tool without installing, as implemented in [#42088](https://github.com/golang/go/issues/42088) and [#40276](https://github.com/golang/go/issues/40276), which can eliminate the need for tools.go.

So maybe `go install tool@version` is enough?

**Comment by akrejcir** [comment]
We discussed this offline.

/lgtm

**Pull request merged**
