### PR TITLE
chore(test): Add CentOS Stream 10 func test.

### PR DESCRIPTION
**Pull request by jcanocan**
**What this PR does / why we need it**:

Adds the required containerdisk infrastructure and a functional test for CentOS Stream 10.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes # [CNV-52778](https://issues.redhat.com/browse/CNV-52778)

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
Please create a new lane for this in project-infra.

/approve
/lgtm

**Comment by lyarwood** [comment]
@jcanocan ^ can you cherry-pick this back to release-1.2 and setup the required lanes?

**Comment by jcanocan** [comment]
> @jcanocan ^ can you cherry-pick this back to release-1.2 and setup the required lanes?

Done. Check https://github.com/kubevirt/common-instancetypes/pull/308

**Pull request merged**
