### PR TITLE
WIP chore: Squash size components

### LINKED ISSUE #38: Flatten instance type directories
/kind enhancement

The current structure is pretty nested and could be simplified, for example: 

```
$ tree common-instancetypes/instancetypes/hyperscale/n/
common-instancetypes/instancetypes/hyperscale/n/
├── 1
│   ├── 2xlarge
│   │   └── kustomization.yaml
│   ├── 4xlarge
│   │   └── kustomization.yaml
│   ├── 8xlarge
│   │   └── kustomization.yaml
│   ├── base
│   │   ├── kustomization.yaml
│   │   └── n1.yaml
│   ├── kustomization.yaml
│   ├── large
│   │   └── kustomization.yaml
│   ├── medium
│   │   └── kustomization.yaml
│   └── xlarge
│       └── kustomization.yaml
├── base
│   ├── kustomization.yaml
│   └── n.yaml
├── kustomization.yaml
└── sizes
    ├── 2xlarge
    │   ├── 2xlarge.yaml
    │   └── kustomization.yaml
    ├── 4xlarge
    │   ├── 4xlarge.yaml
    │   └── kustomization.yaml
    ├── 8xlarge
    │   ├── 8xlarge.yaml
    │   └── kustomization.yaml
    ├── large
    │   ├── kustomization.yaml
    │   └── large.yaml
    ├── medium
    │   ├── kustomization.yaml
    │   └── medium.yaml
    └── xlarge
        ├── kustomization.yaml
        └── xlarge.yaml

17 directories, 24 files
```

As compared to https://github.com/fabiand/instanceTypes/tree/main/series/n1

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #38

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/cc @0xFelix 

Can I also get your thoughts on this approach to resolve https://github.com/kubevirt/common-instancetypes/issues/38?

**Comment by 0xFelix** [comment]
@lyarwood @fabiand 

I like this approach, IMO having less files is very desirable. I would also suggest merging `kustomization.yaml`, `VirtualMachineClusterInstancetype` and `VirtualMachineInstancetype` to have even less files to look at.

E.g. like this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "1"
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "1"

patches:
  - target:
      kind: VirtualMachineClusterInstancetype
    patch: |-
      - op: replace
        path: /kind
        value: VirtualMachineInstancetype
```

**Comment by lyarwood** [comment]
/close

Superseded by #87 and #90

**Pull request closed without merging**
