### PR TITLE
[release-1.0] Revert "Remove Windows 2k12 template"

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This reverts commit 42bdccc936181dde0bf6629ef705634fcef7463c.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Reverted removal of Windows 2k12 from the available preferences
```

### CODE REVIEW

**Comment by ksimon1** [comment]
@0xFelix do we need to revert this in Common templates too?

**Comment by 0xFelix** [comment]
@fabiand Updated the PR description

**Pull request merged**
