### PR TITLE
Reintroduce `dedicatedCPUPlacement` support

### PR DESCRIPTION
**Pull request by lyarwood**
/cc @0xFelix 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
`dedicatedCPUPlacement` support has been reintroduced with recent bugfixes landing in KubeVirt allowing for the use of the attribute in instance types once again.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
@brianmcarey Apologies for the direct ping, any idea why https://github.com/kubevirt/project-infra/pull/2582/files isn't running given the changes to the `run_if_changed` `./common*bundle.yaml` files?

**Comment by lyarwood** [comment]
@0xFelix would you mind reviewing this in the morning, the functest job doesn't automatically run but it is passing after a manual run below:

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_common-instancetypes/31/pull-common-instancetypes-kubevirt-functest/1625540864908464128

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
