### PR TITLE
[release-0.3] centos: Align names with common-templates

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

The previous names of centos.${version}.stream differ from the original common-template names of centos-stream${version}. This change aligns the names again but keeps the dot formatting.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ksimon1** [comment]
How will upgrade work? There will be two the same centos stream instancetypes with different name?

**Comment by lyarwood** [comment]
> How will upgrade work? There will be two the same centos stream instancetypes with different name?

Downstream the original resources will be removed by SSP operator, any VirtualMachines already using the preferences will already have their own copy stashed in ControllerRevisions so their removal will have no impact unless they remove `spec.preference.revisionName` from the VirtualMachine.

**Review by codingben — APPROVED** [review]
/lgtm

**Pull request merged**
