### PR TITLE
Add N Network focused instance type series

### LINKED ISSUE #40: Introduce network workload specific instance types
/kind enhancement

As set out in the following PR for @fabiand's version of common-instancetypes a network specific workload instance type would be useful:

https://github.com/fabiand/instanceTypes/pull/3

Note this includes renaming the neutral / generic instance types.

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This adds the N Network focused instance type series to be used with DPKDK
network intensive applications, like VNFs and DPDK preferences for RHEL{8,9} and CentOS Stream {8,9} to be used with the newly introduced N Network focused instance type series.

It also raises the memory of the kubevirtci cluster to 16G to provide the
necessary resources for functional tests and adds the NUMA feature gate to
'make cluster-up' (was already present in 'make kubevirt-up'). Furthermore
a cpu-topology-spread component to the preferences to allow
configuration of a preferred spread CPU topology.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #40

**Special notes for your reviewer**:

**Release note**:

```release-note
Added N Network focused instance type series
Added DPDK preferences for RHEL{8,9} and CentOS Stream {8,9}
```

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Thank you @0xFelix.
Could you please consider adding a preview of the output instance types / preferences in the CI?
IMO it could increase the number of potential reviewers.

**Review by orelmisan — APPROVED** [review]
Thank you for the changes.

**Comment by 0xFelix** [comment]
Thanks for the reviews!

/approve

**Pull request merged**
